### ISSUE TITLE
add positional information to AST

### ISSUE THREAD

**Issue by Bogdanp** [Bogdanp/elm-ast#13]

**Comment by Bogdanp** [comment]
The changes coming to [combine](https://github.com/Bogdanp/elm-combine/commit/633adc40a7b3a30e6fd298373c3a5680aa5afe08) ought to make this (and dealing with indentation) easier.

**Comment by dynajoe** [comment]
Thoughts on adding Combine.Location to all types? This could be first type parameter or last.

**Comment by wende** [comment]
@joeandaverde That's a good idea. I think that given there might be more information to that in future it'd be nice to add something like
```elm
type alias Meta = {location : Combine.Location}
```
So that we have a place for extension in future without another Major change

**Comment by dynajoe** [comment]
While attempting to make this change it seems that the parser combinator library is not calculating column/line offset correctly. 

See my master branch here 

https://github.com/joeandaverde/elm-ast/

There are times it reports a column of -1. 

For a string input such as  `"x : Int"` it reports line 1 instead of 0.

I very well could have used the library inappropriately (possibly wrong order of operations). I could use another eye on it.

**Comment by wende** [comment]
@joeandaverde 
Hmm. The code looks fine to me. It might be that there is a bug in elm-community/parser-combinators

**Comment by colossoi** [comment]
I'm no expert, but the pull request #84 that Baransu looks like it's done the heavy lifting for this.  Is there someone who could finish off the last remaining 4 items?

**Comment by baransu** [comment]
@laslowh The problem with remaining items is, they are in case of `Variable` and `BinOp` created by hand, without `Parser` context so there is no easy way get metadata. I've created PR counting on community support because I'm out of ideas how this could be done the easy way. Maybe @joeandaverde who initially started working on that could help me out figuring this.
