### ISSUE TITLE
AccessFunction is only a syntactic sugar

### ISSUE THREAD

**Issue by tunguski** [Bogdanp/elm-ast#68]
```elm
fn = .field
{- generates 

   AccessFunction [ field ]

   which is only a syntactic sugar for:
-}
fn = \x -> x.field
{- that generates

   Lambda [ Variable [ "x" ] ] (Access (Variable [ "x" ]) [ field ])

   `x` variable used in example has to be different from `field`; 
   may be generated like field ++ "_"
-}
```

So it seems that additional algebraic element is not needed here. For sake of (model) simplicity it could be removed.

**Comment by jfmengels** [comment]
I'm not sure what you are suggesting.
Are you suggesting that
```elm
fn = .field
{- should generate
  Lambda [ Variable [ "x" ] ] (Access (Variable [ "x" ]) [ "field" ])
-}
```
or that
```elm
fn = \x -> x.field
{- should generate
  AccessFunction [ "field" ]
-}
```
?

Either way, my opinion is that things are fine the way they are now. Having the distinction allows for better analysis. For instance, in a [tool I'm working on](https://github.com/jfmengels/elm-lint#rules) that analyses your code and reports improvable patterns, I report this exact behavior that could be simplified, so that the user can fix it (see SimplifyPropertyAccess). If the AST does that simplification for me, I have no way of knowing how it is written and reporting it to the user.

**Comment by tunguski** [comment]
Hi @jfmengels, you are totally right. Described proposal was based on a specific use case, and as you pointed out it is not proper for general parsing library.

Thanks!

Ps.: it was about removing AccessFunction and to directly write it using simplified type.
