### ISSUE TITLE
Parsing lambdas is extremely slow

### ISSUE THREAD

**Issue by mbuscemi** [Bogdanp/elm-ast#88]
Most of my files parse fairly speedily, but I have noticed that, particularly when I have lambdas, parsing the AST can take an extremely long time. Turning the lambda into a top-level expression solves the compile time problem, but I need to be able to parse lambdas relatively quickly.

Attached is a file that demonstrates the problem. I have verified that it the parser and not my code at http://bogdanp.github.io/elm-ast/example/.

[FileMarkup.elm.txt](https://github.com/Bogdanp/elm-ast/files/1503134/FileMarkup.elm.txt)

**Comment by baransu** [comment]
My guess are not lambdas but multiline function applications. There was PR that reduced that time in some cases (from ~90s for 12 arguments, every in new line, to ~20s) but this is still the issue. Quick solution would be to write elm-ast friendly code without multiline apllications as @wende did in Elchemy while testing self compilation.
The problem is probably in the way we’re parsing those applications. We’re reaching point where JavaScript GC kicks in cleaning incredible high amount of memory which is slowing down everything. You can see it using for example Chrome DevTools flame chart on the demo page.
If you have time and you need it for your usage please concider spending some time on looking into this problem. Maybe you can solve it 🙂
